language: erlang
script: "make travis"
otp_release:
  - 21.0
  - 20.0
  - 19.0
  - 18.2
  - 18.1
  - 18.0
  - 17.4
  - 17.0

addons:
    apt:
        packages:
            - libpam0g-dev
            - libpam-runtime
